### ISSUE TITLE
Fade 2 Grey (Visage) plays incorrectly

### ISSUE THREAD

**Issue by LossyDragon** [libxmp/libxmp#710]
I'm not sure when this module started to play incorrectly, but I know from libxmp 4.4.1 it sounds *mostly* fine. 

Building xmp-cli it seems that channel 14 and 15 are trying to play the notes, but goes quiet as notes become louder and higher pitched. Pattern 7 displays this well and doesnt sound nearly as well as openMPT can play it. 

Building from `master` (and 4.6.0 release) and playing through the SDL example sounds far worse with channels 14/15 becoming mute until the highest volume of those channels are playing (?)

Module in question: https://modarchive.org/index.php?request=view_by_moduleid&query=134790

**Comment by sezero** [comment]
@AliceLR ?

**Comment by AliceLR** [comment]
Just to double check: you built off of the *latest* HEAD? When I run `xmp fade_2_grey_visage.xm -s8` pattern 7 sounds more or less the same as OpenMPT.

I'm ~90% certain this was fixed by 9e25a5c9. When I check out its parent commit, it sounds like what you're describing.

**Comment by LossyDragon** [comment]
I believe so. Before making my report I had a copy from Feb 3rd. But I did grab a fresh copy just to ensure a clean build. 

Below are some videos, I should note that sequence 3 and 4 displays the issue pretty good. Ignore the slight audio popping from the android emulator. But the issue persists on a physical device. 

The 2nd video is through WSL Ubuntu, with its own copy to build and test. 

https://github.com/libxmp/libxmp/assets/4994318/12337f4c-0f7f-4f29-9fc4-329e90425e68

https://github.com/libxmp/libxmp/assets/4994318/10147122-c851-4285-b3a2-a6383dc944f8

AS does throw a few unused warnings, just for the sake of noting it. 
```
ask :app:configureCMakeRelease[arm64-v8a]
C/C++: -- Check for working linker: C:/Users/Lossy/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/ld.lld.exe

> Task :app:mergeLibDexDebug

> Task :app:buildCMakeRelease[arm64-v8a]
C/C++: ninja: Entering directory `C:\Users\Lossy\AndroidStudioProjects\xmp-android\app\.cxx\Release\4k3p1j6x\arm64-v8a'
C/C++: C:/Users/Lossy/AndroidStudioProjects/xmp-android/app/src/main/jni/libxmp/src/depackers/depacker.c:144:12: warning: unused function 'execute_command' [-Wunused-function]
C/C++: static int execute_command(const char * const cmd[], FILE *t)
C/C++:            ^
C/C++: 1 warning generated.

> Task :app:configureCMakeRelease[armeabi-v7a]
C/C++: -- Check for working linker: C:/Users/Lossy/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/ld.lld.exe

> Task :app:buildCMakeRelease[armeabi-v7a]
C/C++: ninja: Entering directory `C:\Users\Lossy\AndroidStudioProjects\xmp-android\app\.cxx\Release\4k3p1j6x\armeabi-v7a'
C/C++: C:/Users/Lossy/AndroidStudioProjects/xmp-android/app/src/main/jni/libxmp/src/depackers/depacker.c:144:12: warning: unused function 'execute_command' [-Wunused-function]
C/C++: static int execute_command(const char * const cmd[], FILE *t)
C/C++:            ^
C/C++: 1 warning generated.

> Task :app:mergeExtDexDebug

> Task :app:configureCMakeRelease[x86]
C/C++: -- Check for working linker: C:/Users/Lossy/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/ld.lld.exe

> Task :app:buildCMakeRelease[x86]
C/C++: ninja: Entering directory `C:\Users\Lossy\AndroidStudioProjects\xmp-android\app\.cxx\Release\4k3p1j6x\x86'
C/C++: C:/Users/Lossy/AndroidStudioProjects/xmp-android/app/src/main/jni/libxmp/src/depackers/depacker.c:144:12: warning: unused function 'execute_command' [-Wunused-function]
C/C++: static int execute_command(const char * const cmd[], FILE *t)
C/C++:            ^
C/C++: 1 warning generated.

> Task :app:configureCMakeRelease[x86_64]
C/C++: -- Check for working linker: C:/Users/Lossy/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/ld.lld.exe

> Task :app:buildCMakeRelease[x86_64]
C/C++: ninja: Entering directory `C:\Users\Lossy\AndroidStudioProjects\xmp-android\app\.cxx\Release\4k3p1j6x\x86_64'
C/C++: C:/Users/Lossy/AndroidStudioProjects/xmp-android

/app/src/main/jni/libxmp/src/depackers/depacker.c:144:12: warning: unused function 'execute_command' [-Wunused-function]
C/C++: static int execute_command(const char * const cmd[], FILE *t)
C/C++:            ^

C/C++: 1 warning generated.
```

**Comment by AliceLR** [comment]
Okay, got it. Those are channels 8 and 9. Channels 14/15 had a different bug which was fixed in the commit I linked. I'll look into it.

**Comment by AliceLR** [comment]
The intended behavior here is in position 3 both channels play the same note with the same sine wave, but channel 9 is played and then pitch shifted slightly after channel 8, resulting in an out-of-phase chorus-like effect. As they both approach their final pitch in position 4, they gradually hard pan, which prevents them from negating each other.

For SOME REASON in libxmp, they seem to negate each other early, and don't become audible again until the pan starts in position 4.

**Comment by AliceLR** [comment]
Turns out 9e25a5c9e4a62178c035dcc3cd0d65f8f76552c2, which fixed the issue in pattern 7, either caused or revealed the issue in positions 3 and 4. :(

**Comment by AliceLR** [comment]
Got it. There's an old bit of code leftover in the envelope handlers that, for some reason, turned off the sustain loop when it exists on the loop end. This is of course nonsense, and because the regular loop has its start and end on the same point, it does effectively nothing (XM quirk that was fixed by the aforementioned patch). The instrument was running past the loop to a silent part of the volume envelope and then it would get VERY loud after 100 or so ticks.

**Comment by LossyDragon** [comment]
I loaded the changes from that PR into my app and it sounds SO MUCH better! Thank you! ❤️
